name: 'storage-mongo-mocha'

volumes:
  mongodb-data-mocha:
  solr-data-mocha:

services:
  rbportal:
    environment:
      - sails_redbox__mochaTesting=true
      - 'CI=${CI:-false}'
    entrypoint:
      - '/opt/redbox-portal/node_modules/@researchdatabox/sails-hook-redbox-storage-mongo/support/run-mocha.sh'

  mongodb:
    volumes:
      - 'mongodb-data-mocha:/data/db'

  solr:
    volumes:
      - 'solr-data-mocha:/var/solr/data'
